### ISSUE TITLE
Page crashes when cycling through some chord diagrams

### ISSUE THREAD

**Issue by zachpmanson** [BenoitBellegarde/UltimateTab#29]
https://ultimate-tab.com/tab/peach-pit/alrighty-aphrodite-chords-2083783

Repro:
- click on any of the chords
- keep clicking next chord
- seems to crash when viewing the last chord in the cycle

**Comment by BenoitBellegarde** [comment]
Hi @zachpmanson, thanks for your bug report, the issue has been resolved! 👍
