### ISSUE TITLE
Favourite tabs can be loaded straight from localStorage

### ISSUE THREAD

**Issue by zachpmanson** [BenoitBellegarde/UltimateTab#30]
Given that favourited tabs are stored entirely in localstorage, this could be used as a cache so that the backend doesn't need to spin up and run the lamdba functions every time.

Would definitely cut down the number of requests since I'm probably looking at favourites most often.

(even better would be a database sitting between end user and UG that stores all tabs after they are scraped so that they only ever need to be scraped from UG once, although this data would become stale eventually)

**Comment by BenoitBellegarde** [comment]
Hi @zachpmanson, thanks for your reply, the issue has been resolved! 👍

You're absolutely right about having a database to store all the data, but that is a bit risky because UG could interpret it as stealing their data (and I definitely don’t want any legal trouble😄).
