### ISSUE TITLE
Show the song key as well as the capo location (If available on the UG official webpage), and allow for visualizing the piano chords instead

### ISSUE THREAD

**Issue by WassimJabz** [BenoitBellegarde/UltimateTab#33]
These changes would open up this platform to all piano players (Capo location is required to ensure the correct transposition is performed)

**Comment by BenoitBellegarde** [comment]
Hi @WassimJabz , I've added the song key and capo location to the tabs when the information is available. It will take me a bit of time to display the piano chords, though—I need to find the right library to display them properly. I'll keep you updated. 👍

**Comment by WassimJabz** [comment]
Thank you for the work! This project is incredibly useful to the music community :)
