### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by xpufx** [BenoitBellegarde/UltimateTab#36]
Do you have a docker image and a docker compose file for this project?

**Comment by BenoitBellegarde** [comment]
Hi xpufx, unfortunately, I don’t have a Docker image at the moment. I’m not very familiar with the tool and haven’t had the time to dive into it to figure out how to properly configure the project for it. However, someone forked the project a while ago with the intention of adding a Docker image: 
https://github.com/cyhyraethz/NeoTab/blob/main/Dockerfile
https://github.com/cyhyraethz/NeoTab/blob/main/docker-compose.yml

Feel free to take a look and see if it helps. If you manage to build one, don’t hesitate to submit a pull request to integrate it into the project—it would be awesome! :)
