### ISSUE TITLE
feature request: font size

### ISSUE THREAD

**Issue by gasinkas** [BenoitBellegarde/UltimateTab#38]
Hey, amazing project. Could you add the feature to change the font size?

On iPad its sometimes hard to read it (if you don't want to touch the display with your nose). 
The Browser-Zoom is kinda weird when autoscroll in enabled.

Thanks :)

**Comment by BenoitBellegarde** [comment]
Hey @gasinkas thanks for your support ! 
I just added the feature on the tab page : 

![image](https://github.com/user-attachments/assets/6af7f4e8-149c-4d9b-a977-df9db0fdb18c)

Hope you'll enjoy it :)
