### ISSUE TITLE
feature request: clean search with x

### ISSUE THREAD

**Issue by gasinkas** [BenoitBellegarde/UltimateTab#40]
Hello again :) 

Maybe it's helpful to add the following feature: add an (x) for removing all text input in the searchbox. Its faster then backspace backspace backspace ... expecially on mobile devices.

Workaround so far is: Click on the Logo top left and click on search bar. Still faster than removing the whole text :D 

Greeeetings again :)

**Comment by BenoitBellegarde** [comment]
Hi @gasinkas, the button has been added and is compatible with all browsers! If you don't see the button, don't hesitate to clear your browser cache and try again ;)

![image](https://github.com/user-attachments/assets/73544e0f-54e3-4662-8eef-ee49f710dd16)
