### ISSUE TITLE
Bug: checkboxProps not a function

### ISSUE THREAD

**Issue by PeterCassell92** [BenoitBellegarde/UltimateTab#42]
When clicking the 'GetStarted' button from the home page, which appears to lead to the /search route, an error occurs.

The error TypeError: _getCheckboxProps_ is not a function 

is displayed.

Upon inspection, this is because _getCheckboxProps_ is being deconstructed from the _useRadio()_ function of chakra-ui. It should instead be sourcing this from the _useCheckbox()_ function I believe.

**Comment by PeterCassell92** [comment]
https://github.com/BenoitBellegarde/UltimateTab/pull/43

**Comment by BenoitBellegarde** [comment]
Hi @PeterCassell92, I don't really understand why I don't get this error on my localhost or on my VPS, but you're absolutely right about the modification. Thank you for your contribution !
